"""
SA6b — Proper Conditional Logistic Case-Crossover (real OR per °C)
=================================================================

Why this exists
---------------
The original ``sa6_case_crossover.py`` reports a within-person temperature
DIFFERENCE (case vs control days) and a Spearman correlation, but it does
NOT fit a conditional logistic regression, so it never produces an odds
ratio. The manuscript's "OR 1.08 per degC, 95% CI 1.02-1.14" is therefore
not generated by the code. This script computes a genuine conditional
logistic (case-crossover) OR per degC, reusing the SAME data loader and the
SAME strata/case definitions as SA6 so the result is directly comparable.

Design (time-stratified, within-person)
---------------------------------------
  * Stratum   = patient x calendar month (patient is their own control;
                removes time-invariant confounding + coarse season).
  * Case      = a visit on which the biomarker is >= that patient's own
                75th percentile (same definition as SA6).
  * Exposure  = same-day temperature (temp_lag_0d), modelled per 1 degC.
  * Estimator = statsmodels ConditionalLogit conditioned on stratum.
  * Only informative strata (containing >=1 case AND >=1 control) contribute
    to the conditional likelihood, as in any matched/conditional design.

NOTE / honest limitation: like SA6, control "days" here are the patient's
OTHER VISIT days within the month, because daily temperature on non-visit
days is not in the analysis dataset. This is a within-person visit-based
case-crossover, not a referent-day design. State this in the Methods.

Run
---
    cd <repo root>
    pip install statsmodels   # if not already installed
    python sa6b_conditional_logistic_or.py

Outputs
-------
  * Prints OR (per degC), 95% CI, p, and counts for viral_load and cd4_count.
  * Writes mcd_outputs/sensitivity/sa6_case_crossover/sa6b_conditional_logistic.json
  * Prints a manuscript-ready sentence you can paste in (replacing the
    unsupported OR).
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

import numpy as np
import pandas as pd

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)

TEMP_COL = "temp_lag_0d"          # same-day temperature, per degC (as in SA6)
THRESHOLD_QUANTILE = 0.75          # "case" = >= patient's own 75th percentile
BIOMARKERS = ["viral_load", "cd4_count"]


def _build_engineered_df() -> pd.DataFrame:
    """Reuse the pipeline's own loader so columns match SA6 exactly."""
    from mcd_pipeline.stage0_data_prep.build_analysis_dataset import build_analysis_dataset
    from mcd_pipeline.stage0_data_prep.feature_engineering import engineer_features
    from mcd_pipeline.stage0_data_prep.biomarker_definitions import get_available_biomarkers

    df = build_analysis_dataset()
    biomarkers = get_available_biomarkers()
    bio_cols = [b.column for b in biomarkers.values() if b.column and b.column in df.columns]
    return engineer_features(df, bio_cols)


def _make_strata(df: pd.DataFrame) -> pd.DataFrame:
    """Patient x year-month strata (reuse SA6's helper if importable)."""
    try:
        from mcd_pipeline.sensitivity.sa6_case_crossover import _create_case_crossover_strata
        return _create_case_crossover_strata(df)
    except Exception:
        d = df.copy()
        d["visit_date"] = pd.to_datetime(d["visit_date"])
        d["year_month"] = d["visit_date"].dt.to_period("M")
        d["stratum"] = d["patient_id"].astype(str) + "_" + d["year_month"].astype(str)
        return d


def _pick_temp_col(df: pd.DataFrame) -> str:
    if TEMP_COL in df.columns:
        return TEMP_COL
    # fall back to any same-day temperature column
    for c in ("dlnm_lag0_c", "era5_temp_lag0d_c", "temp_mean_c"):
        if c in df.columns:
            logger.warning("temp_lag_0d not found; using %s", c)
            return c
    raise KeyError("No same-day temperature column found (temp_lag_0d / dlnm_lag0_c / temp_mean_c).")


def conditional_logistic_or(df_cc: pd.DataFrame, bio: str, temp_col: str) -> dict:
    from statsmodels.discrete.conditional_models import ConditionalLogit

    d = df_cc[df_cc[bio].notna()].copy()
    if len(d) < 100:
        return {"status": "insufficient_data", "n": int(len(d))}

    # within-patient case definition (same as SA6)
    thr = d.groupby("patient_id")[bio].transform(lambda x: x.quantile(THRESHOLD_QUANTILE))
    d["case"] = (d[bio] >= thr).astype(int)

    cc = d[["case", temp_col, "stratum"]].dropna()
    # informative strata only: must contain both a case and a control
    nun = cc.groupby("stratum")["case"].transform("nunique")
    cc = cc[nun > 1]
    if cc["stratum"].nunique() < 20 or cc["case"].nunique() < 2:
        return {"status": "insufficient_informative_strata",
                "n_informative_strata": int(cc["stratum"].nunique())}

    model = ConditionalLogit(cc["case"].to_numpy(),
                             cc[[temp_col]].to_numpy(),
                             groups=cc["stratum"].to_numpy())
    res = model.fit(disp=0)
    beta = float(res.params[0])
    lo, hi = (float(x) for x in res.conf_int()[0])
    return {
        "status": "success",
        "exposure": f"{temp_col} (per 1 degC)",
        "or_per_degree": float(np.exp(beta)),
        "or_ci_lower": float(np.exp(lo)),
        "or_ci_upper": float(np.exp(hi)),
        "p_value": float(res.pvalues[0]),
        "n_observations": int(len(cc)),
        "n_informative_strata": int(cc["stratum"].nunique()),
        "n_cases": int(cc["case"].sum()),
        "n_controls": int((cc["case"] == 0).sum()),
        "threshold_quantile": THRESHOLD_QUANTILE,
    }


def main() -> None:
    df = _build_engineered_df()
    temp_col = _pick_temp_col(df)
    df_cc = _make_strata(df)

    results = {}
    for bio in BIOMARKERS:
        if bio not in df_cc.columns:
            results[bio] = {"status": "column_not_found"}
            logger.info("%-12s : column not found", bio)
            continue
        r = conditional_logistic_or(df_cc, bio, temp_col)
        results[bio] = r
        if r.get("status") == "success":
            logger.info(
                "%-12s : OR %.3f per degC (95%% CI %.3f-%.3f), p=%.4g  "
                "[%d informative strata, %d cases / %d controls]",
                bio, r["or_per_degree"], r["or_ci_lower"], r["or_ci_upper"],
                r["p_value"], r["n_informative_strata"], r["n_cases"], r["n_controls"],
            )
        else:
            logger.info("%-12s : %s", bio, r.get("status"))

    out_dir = Path("mcd_outputs/sensitivity/sa6_case_crossover")
    out_dir.mkdir(parents=True, exist_ok=True)
    out = out_dir / "sa6b_conditional_logistic.json"
    out.write_text(json.dumps(
        {"analysis": "sa6b_conditional_logistic_case_crossover",
         "design": "within-person, stratum = patient x calendar month, case = >= patient 75th pct, "
                   "exposure = same-day temperature per degC, estimator = conditional logistic",
         "per_biomarker": results}, indent=2, default=str))
    logger.info("\nSaved %s", out)

    vl = results.get("viral_load", {})
    if vl.get("status") == "success":
        logger.info(
            "\nManuscript-ready sentence:\n"
            "  Within-person case-crossover (SA5) gave an adjusted odds ratio of "
            "%.2f per 1 degC (95%% CI %.2f-%.2f; p=%.4f) for a viral-load reading "
            "above the patient's 75th percentile.",
            vl["or_per_degree"], vl["or_ci_lower"], vl["or_ci_upper"], vl["p_value"])


if __name__ == "__main__":
    main()
