"""
Central Configuration — MCD Pipeline Parameters
================================================

All tuneable parameters from the Manuscript Concept Document in one place.
Import this module rather than hard-coding values in analysis scripts.

MCD reference: "Heat, Vulnerability, and the Body: Multi-System Biomarker
Signatures of Temperature Exposure in Johannesburg Revealed Through
Explainable Machine Learning" — Parker et al. (2026)
"""

from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parent.parent

FINAL_DATASETS = PROJECT_ROOT / "FINAL_DATASETS"
ANALYSIS_READY_CSV = FINAL_DATASETS / "JOHANNESBURG_CLINICAL_ANALYSIS_READY.csv"
CLINICAL_FULL_CSV = FINAL_DATASETS / "JOHANNESBURG_CLINICAL_FULL.csv"
GCRO_CSV = FINAL_DATASETS / "GCRO_SOCIOECONOMIC_CLIMATE_ENHANCED_LABELED.csv"

INDIVIDUAL_STUDIES_DIR = FINAL_DATASETS / "INDIVIDUAL_STUDIES"
CLIMATE_LINKED_DIR = (
    FINAL_DATASETS / "CLIMATE_HEALTH_LINKAGE" / "JHB_CLIMATE_LINKAGE"
    / "linked_datasets"
)
SES_MATCHED_DIR = FINAL_DATASETS / "SOCIOECONOMIC_LINKAGE" / "matched_datasets"
METADATA_DIR = FINAL_DATASETS / "metadata"

# Tidy (long-format) datasets — canonical pipeline inputs
TIDY_DIR = FINAL_DATASETS / "TIDY_DATASETS"
TIDY_BIOMARKERS_CSV = TIDY_DIR / "TIDY_clinical_biomarkers.csv"
TIDY_CLIMATE_CSV = TIDY_DIR / "TIDY_climate_variables.csv"
TIDY_DEMOGRAPHICS_CSV = TIDY_DIR / "TIDY_demographics.csv"
TIDY_SOCIOECONOMIC_CSV = TIDY_DIR / "TIDY_socioeconomic.csv"
TIDY_HVI_CSV = TIDY_DIR / "TIDY_hvi.csv"

CLIMATE_ZARR_BASE = Path("/home/cparker/selected_data_all/data/RP2_subsets/JHB")

# MODIS LST linkage (generated by mcd_pipeline/utils/extract_modis_lst.py)
MODIS_LST_CSV = FINAL_DATASETS / "CLIMATE_HEALTH_LINKAGE" / "MODIS_LST_LINKAGE.csv"

# MERRA-2 PM2.5 linkage (generated by mcd_pipeline/utils/extract_merra2_pollution.py)
# NASA MERRA-2 aerosol reanalysis; sum of 5 PM2.5 components; ~55 km resolution
MERRA2_POLLUTION_CSV = FINAL_DATASETS / "CLIMATE_HEALTH_LINKAGE" / "MERRA2_POLLUTION_LINKAGE.csv"

# ERA5-Land linkage (generated by mcd_pipeline/utils/extract_era5_land.py)
# ECMWF ERA5-Land daily 2-m air temperature at ~9 km (0.1°) — intermediate
# resolution between primary ERA5 (~31 km) and MODIS LST (1 km).
ERA5_LAND_CSV = FINAL_DATASETS / "CLIMATE_HEALTH_LINKAGE" / "ERA5_LAND_LINKAGE.csv"

# ---------------------------------------------------------------------------
# Primary exposure switch (added 2026-06-08 for full ERA5-Land pipeline rerun)
# ---------------------------------------------------------------------------
# "era5"      → primary lag features come from dlnm_lag*_c (DLNM-extracted ERA5
#               at ~31 km, the original primary). Outputs go to mcd_outputs/.
# "era5_land" → primary lag features come from era5land_temp_lag*d_c (ERA5-Land
#               at ~9 km). Outputs go to mcd_outputs_era5_land/.
# This flag is read by select_lag_features() in stage0_data_prep/feature_engineering.py
# and by anything that resolves OUTPUT_ROOT below.
import os as _os
PRIMARY_EXPOSURE_SOURCE = _os.environ.get("RP2_PRIMARY_EXPOSURE", "era5")
assert PRIMARY_EXPOSURE_SOURCE in ("era5", "era5_land"), (
    f"PRIMARY_EXPOSURE_SOURCE must be 'era5' or 'era5_land', got {PRIMARY_EXPOSURE_SOURCE}"
)

# Output root depends on primary exposure so that re-runs don't overwrite the
# canonical primary-ERA5 results.
OUTPUT_ROOT = PROJECT_ROOT / (
    "mcd_outputs" if PRIMARY_EXPOSURE_SOURCE == "era5" else "mcd_outputs_era5_land"
)
PUBLICATION_ROOT = PROJECT_ROOT / "mcd_publication"

# ---------------------------------------------------------------------------
# Temperature Lag Windows (MCD Section: Analysis Plan)
# ---------------------------------------------------------------------------

# Individual day lags used as XGBoost features
LAG_DAYS = [0, 1, 3, 7, 14, 21, 30]

# Column names in climate-linked datasets for these lags.
# DLNM-extracted lags go up to 21 days; lag 30 uses the ERA5 rolling mean.
_DLNM_LAG_COLUMNS = [f"dlnm_lag{d}_c" for d in LAG_DAYS if d <= 21]
LAG_FEATURE_COLUMNS = _DLNM_LAG_COLUMNS + ["era5_temp_lag30d_c"]

# Rolling mean lag columns (supplementary features)
ROLLING_LAG_COLUMNS = [
    "era5_temp_lag1d_c",
    "era5_temp_lag3d_c",
    "era5_temp_lag7d_c",
    "era5_temp_lag14d_c",
    "era5_temp_lag30d_c",
]

# Diurnal temperature range (additional climate feature per MCD)
DTR_COLUMN = "era5_temp_range_c"

# ---------------------------------------------------------------------------
# Covariates (MCD Section: Analysis Plan)
# ---------------------------------------------------------------------------

DEMOGRAPHIC_COVARIATES = ["age_years", "sex"]
CLINICAL_COVARIATES = ["hiv_status"]
SOCIOECONOMIC_COVARIATES = [
    "gcro_dwelling_type",
    "gcro_income_bracket",
    "gcro_education_level",
    "gcro_employment_status",
]

# Temporal confounders
# Month fixed effects: one-hot encoded month (1–12)
# Fourier seasonality: sin(2πm/12), cos(2πm/12) for m = month
# Calendar year: integer year
# Study ID: categorical study identifier
TEMPORAL_CONFOUNDERS = ["month", "year", "study_source"]
# Fourier terms are computed in feature_engineering.py

# ---------------------------------------------------------------------------
# XGBoost Model Parameters (MCD: Primary Analysis)
# ---------------------------------------------------------------------------

XGBOOST_PARAMS = {
    "n_estimators": 500,
    "max_depth": 6,
    "learning_rate": 0.05,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "min_child_weight": 5,
    "reg_alpha": 0.1,
    "reg_lambda": 1.0,
    "random_state": 42,
    "n_jobs": -1,
}

# Cross-validation: GroupKFold by patient_id (prevents patient leakage)
CV_FOLDS = 5
PATIENT_ID_COLUMN = "patient_id"

# ---------------------------------------------------------------------------
# Bootstrap Parameters (MCD: 50 model replicates)
# ---------------------------------------------------------------------------

N_BOOTSTRAP_REPLICATES = 50           # Model replicates for SHAP stability (MCD spec)
N_BOOTSTRAP_FAST = 10                 # Exploratory run (use --fast flag)
N_BOOTSTRAP_SENSITIVITY = 10          # Sensitivity analysis bootstrap replicates
BOOTSTRAP_RANDOM_SEED = 42            # Single source-of-truth seed — used everywhere
N_PARALLEL_JOBS = -1                  # Bootstrap parallelism: -1 = all cores

# ---------------------------------------------------------------------------
# Concordance Thresholds — sensitivity analysis validation
# ---------------------------------------------------------------------------
# Spearman ρ ≥ 0.7: same-method comparison (XGBoost-SHAP under different data).
# Spearman ρ ≥ 0.5: cross-method comparison (DLNM vs SHAP — methods measure
#   different quantities so a lower bar is appropriate; Gasparrini 2010).
CONCORDANCE_RHO_THRESHOLD = 0.7       # SA2–SA8: same-method, different data
CONCORDANCE_RHO_DLNM = 0.5           # SA1: cross-method (DLNM vs SHAP)
MIN_SUBSET_ROWS = 500                 # Minimum rows for a SA subset to be valid

# ---------------------------------------------------------------------------
# SHAP Configuration (MCD: TreeSHAP with interventional conditional expectation)
# ---------------------------------------------------------------------------

# Physiological plausibility caps — applied at data ingest (Stage 0)
# Values outside these bounds are set to NaN (treated as missing).
# Sources: clinical reference ranges + unit consistency checks.
# LDL 417 mmol/L confirmed unit error (should be mg/dL); cap at 15 mmol/L.
BIOMARKER_CAPS = {
    "ldl_cholesterol":      (0.5, 15.0),   # mmol/L: FH max ~12, cap at 15
    "total_cholesterol":    (1.0, 20.0),   # mmol/L
    "hdl_cholesterol":      (0.2, 5.0),    # mmol/L
    "triglycerides":        (0.1, 30.0),   # mmol/L
    "creatinine":           (10,  2000),   # µmol/L
    "fasting_glucose":      (1.0, 50.0),   # mmol/L
    "hba1c":                (3.0, 20.0),   # %
    "hemoglobin":           (2,   25),     # g/dL (data unit — NOT g/L)
    "hematocrit":           (10,  70),     # %
    "albumin":              (10,  70),     # g/L
    "alt":                  (1,   5000),   # U/L
    "ast":                  (1,   5000),   # U/L
    "systolic_bp":          (50,  300),    # mmHg
    "diastolic_bp":         (20,  200),    # mmHg
    "heart_rate":           (20,  250),    # bpm
    "bmi":                  (10,  80),     # kg/m²
}

SHAP_FEATURE_PERTURBATION = "interventional"  # NOT "tree_path_dependent"
SHAP_BACKGROUND_SAMPLES = 1000  # Background rows for interventional marginalisation
# 1000 verified sufficient: lag-feature Spearman r ≥ 0.90 vs full background.
# 500 caused borderline failures for flat lag profiles (creatinine, systolic_bp).
# Set to None to use the full dataset (original behaviour, ~15x slower)
# This marginalises over the empirical feature distribution rather than
# conditioning on correlated neighbours — critical for correlated lag features.
# Reference: Janzing, Minorics & Blöbaum (2020) "Feature relevance
# quantification in explainable AI"

# ---------------------------------------------------------------------------
# Stage 2: Interaction Detection (MCD Section)
# ---------------------------------------------------------------------------

N_PERMUTATIONS = 500  # Per biomarker model
FDR_THRESHOLD = 0.10  # Benjamini-Hochberg q-value
TOP_INTERACTIONS = 50  # Rank top N interactions per biomarker

# ---------------------------------------------------------------------------
# Stage 3: Vulnerability Clustering (MCD Section)
# ---------------------------------------------------------------------------

PCA_VARIANCE_THRESHOLD = 0.85  # Retain components explaining 85% variance (archival)
PCA_CLUSTERING_DIMS = 10       # Top N PCs for clustering (balances signal vs noise)
# Refinement (April 2026): 56 PCs → curse of dimensionality for k-means (ARI=0.377).
# Top 10 PCs (~38% variance) + GMM gives ARI=0.993.
KMEANS_K_RANGE = range(3, 9)   # k = 3, 4, 5, 6, 7, 8 (supplementary comparison)
GMM_N_COMPONENTS = 3           # Primary clustering method (justified by refinement)
GMM_COVARIANCE_TYPE = "full"   # Allows elliptical clusters in SHAP space
CLUSTER_STABILITY_ITERATIONS = 500
CLUSTER_STABILITY_THRESHOLD = 0.80

# ---------------------------------------------------------------------------
# Multiple Testing Correction (MCD Section)
# ---------------------------------------------------------------------------

# Primary: Bonferroni across 8 biomarker systems
N_BIOMARKER_SYSTEMS = 8
BONFERRONI_ALPHA = 0.05 / N_BIOMARKER_SYSTEMS  # = 0.00625

# Secondary: FDR within significant systems and for interactions
FDR_Q_WITHIN_SYSTEMS = 0.10

# ---------------------------------------------------------------------------
# Sensitivity Analysis Flags
# ---------------------------------------------------------------------------

SENSITIVITY_ANALYSES = {
    "sa1_dlnm": True,           # DLNM validation for top 5 biomarkers
    "sa2_modis_vs_era5": True,  # MODIS LST vs ERA5
    "sa3_pollution": True,      # Pollution-adjusted subset (2007–2021)
    "sa4_covid": True,          # COVID-19 period exclusion (2020–2021)
    "sa5_imputation": True,     # KNN vs MICE vs complete-case (code complete)
    "sa6_case_crossover": True, # Case-crossover for CD4/viral load
    "sa7_hiv_stratified": True, # HIV cohorts vs general population
    "sa8_heatwave": True,       # 95th vs 90th percentile threshold
}

# SA3: pollution-adjusted subset year range
POLLUTION_DATA_START_YEAR = 2007
POLLUTION_DATA_END_YEAR = 2021

# SA4: COVID exclusion years
COVID_EXCLUSION_YEARS = [2020, 2021]

# SA8: heatwave percentile thresholds to compare
HEATWAVE_PERCENTILES = [90, 95]

# ---------------------------------------------------------------------------
# Random Seeds for Reproducibility
# ---------------------------------------------------------------------------

MASTER_SEED = 42
