"""
SA12: ERA5-Land vs Primary ERA5 — Intermediate-Resolution Reanalysis Sensitivity
================================================================================

Re-runs Stage 1 using ECMWF/ERA5_LAND/DAILY_AGGR daily 2-m air temperature
(~9 km, 0.1°) instead of the primary ERA5 reanalysis (~31 km, 0.25°). Designed
to bracket the resolution spectrum alongside SA2 MODIS LST (~1 km):

    Primary ERA5  ~31 km  air temp, hourly→daily   — main analysis
    ERA5-Land     ~9 km   air temp, daily          — this SA (SA12)
    MODIS LST     ~1 km   land surface temp, daily — SA2

Comparing ERA5-Land vs primary ERA5 holds the underlying physics fixed (both
ECMWF reanalysis, same data assimilation system) and varies only spatial grid.
Comparing ERA5-Land vs MODIS varies both grid AND product type (reanalysis-2m-air
vs satellite-LST), which the design of SA2 conflates. Together the two SAs
disentangle "spatial resolution" from "reanalysis vs satellite."

Concordance of ERA5-Land SHAP lag profiles with primary ERA5 indicates
whether the ~3× spatial-resolution upgrade materially shifts the
biomarker–temperature signal. High concordance → resolution was not driving
the SA2 discordance; product type was. Low concordance → resolution itself
matters and ERA5-Land may be a more appropriate primary exposure for an
urban-scale paper.

Data: FINAL_DATASETS/CLIMATE_HEALTH_LINKAGE/ERA5_LAND_LINKAGE.csv
      (generated by `python -m mcd_pipeline.utils.extract_era5_land`).
"""

import json
import logging
from pathlib import Path

import pandas as pd

from mcd_pipeline import config
from mcd_pipeline.sensitivity._sensitivity_core import (
    compare_lag_profiles,
    load_primary_lag_profiles,
    run_lightweight_stage1,
)

logger = logging.getLogger(__name__)

# ERA5-Land lag column pattern: era5land_temp_lag0d_c, era5land_temp_lag1d_c, ...
ERA5LAND_LAG_COLS = [f"era5land_temp_lag{d}d_c" for d in config.LAG_DAYS]
# Primary lag columns used as model features (standardised names).
PRIMARY_LAG_COLS = [f"temp_lag_{d}d" for d in config.LAG_DAYS]


def _load_era5_land_data() -> pd.DataFrame | None:
    """Load ERA5-Land linkage CSV if it exists."""
    if not config.ERA5_LAND_CSV.exists():
        return None
    logger.info("Loading ERA5-Land data from %s...", config.ERA5_LAND_CSV)
    df = pd.read_csv(config.ERA5_LAND_CSV, low_memory=False)
    logger.info(
        "  ERA5-Land rows: %d, coverage: %.1f%%",
        len(df),
        df["era5land_temp_lag0d_c"].notna().mean() * 100,
    )
    return df


def _swap_primary_for_era5_land(
    df: pd.DataFrame,
    land_df: pd.DataFrame,
) -> pd.DataFrame:
    """Replace primary ERA5 lag features with ERA5-Land lag features.

    Merges on (study_source, patient_id, visit_date), then renames
    era5land_temp_lag*d_c → temp_lag_*d so that the existing Stage 1
    infrastructure (which expects temp_lag_*d as features) works unchanged.
    """
    df = df.copy()
    df["visit_date"] = df["visit_date"].astype(str)
    land_df = land_df.copy()
    land_df["visit_date"] = land_df["visit_date"].astype(str)

    merged = df.merge(
        land_df[["study_source", "patient_id", "visit_date"] + ERA5LAND_LAG_COLS],
        on=["study_source", "patient_id", "visit_date"],
        how="left",
    )

    coverage = merged["era5land_temp_lag0d_c"].notna().mean() * 100
    logger.info("  ERA5-Land merge coverage: %.1f%% of patient-visits", coverage)
    if coverage < 95:
        logger.warning(
            "  Low ERA5-Land coverage (%.1f%%) — investigate before trusting results",
            coverage,
        )

    # Drop primary temp_lag_*d columns first to avoid duplicate-name DataFrames.
    merged = merged.drop(columns=[c for c in PRIMARY_LAG_COLS if c in merged.columns])

    rename_map = {
        f"era5land_temp_lag{d}d_c": f"temp_lag_{d}d" for d in config.LAG_DAYS
    }
    merged = merged.rename(columns=rename_map)

    n_before = len(merged)
    merged = merged.dropna(subset=["temp_lag_0d"])
    n_after = len(merged)
    logger.info(
        "  Rows with ERA5-Land data: %d/%d (%.1f%%)",
        n_after, n_before, 100 * n_after / n_before,
    )
    return merged


def run_era5_land_comparison(
    df: pd.DataFrame,
    output_dir: Path = None,
    primary_profiles: dict = None,
) -> dict:
    """Re-run Stage 1 with ERA5-Land features and compare SHAP profiles."""
    output_dir = output_dir or (config.OUTPUT_ROOT / "sensitivity")
    sa_output = output_dir / "sa12_era5land"
    sa_output.mkdir(parents=True, exist_ok=True)

    logger.info("=== SA12: ERA5-Land (~9 km) vs Primary ERA5 (~31 km) ===")

    land_df = _load_era5_land_data()
    if land_df is None:
        msg = (
            f"ERA5-Land file not found at {config.ERA5_LAND_CSV}. "
            "Run `python -m mcd_pipeline.utils.extract_era5_land` to generate it."
        )
        logger.warning("  %s", msg)
        summary = {
            "sensitivity_analysis": "sa12_era5_land",
            "status": "data_unavailable",
            "description": msg,
            "era5_land_csv_path": str(config.ERA5_LAND_CSV),
        }
        with open(sa_output / "sa12_summary.json", "w") as f:
            json.dump(summary, f, indent=2)
        return summary

    df_land = _swap_primary_for_era5_land(df, land_df)

    if len(df_land) < 1000:
        summary = {
            "sensitivity_analysis": "sa12_era5_land",
            "status": "insufficient_data",
            "n_rows_after_merge": len(df_land),
        }
        with open(sa_output / "sa12_summary.json", "w") as f:
            json.dump(summary, f, indent=2)
        return summary

    if primary_profiles is None:
        primary_profiles = load_primary_lag_profiles()

    logger.info("  Running lightweight Stage 1 with ERA5-Land temperature features...")
    land_results = run_lightweight_stage1(
        df_land,
        output_dir=sa_output / "era5land_stage1",
        label="sa12_era5land",
    )

    concordance: dict = {}
    for bio_name, result in land_results.items():
        if "error" in result:
            concordance[bio_name] = {"status": "failed", "error": result["error"]}
            continue
        lag_summary_land = result.get("lag_summary")
        primary_lag = primary_profiles.get(bio_name)
        if lag_summary_land is None or primary_lag is None:
            concordance[bio_name] = {"status": "no_comparison"}
            continue
        cmp = compare_lag_profiles(primary_lag, lag_summary_land)
        cmp["cv_r2_era5_land"] = result.get("cv_r2")
        cmp["temporal_window_era5_land"] = result.get("temporal_window")
        concordance[bio_name] = cmp

    concordant = [b for b, c in concordance.items() if c.get("concordant", False)]
    rhos = [c["spearman_rho"] for c in concordance.values()
            if isinstance(c.get("spearman_rho"), float)]

    summary = {
        "sensitivity_analysis": "sa12_era5_land",
        "description": (
            "Re-fit Stage 1 with ERA5-Land (~9 km) replacing primary ERA5 (~31 km) "
            "as the temperature exposure; SHAP lag profiles compared to primary."
        ),
        "n_rows_after_merge": int(len(df_land)),
        "n_patients_era5_land": int(
            df_land["patient_id"].nunique() if "patient_id" in df_land.columns else 0
        ),
        "n_biomarkers_compared": len(concordance),
        "n_biomarkers_concordant": len(concordant),
        "concordant_biomarkers": concordant,
        "mean_spearman_rho": float(sum(rhos) / len(rhos)) if rhos else None,
        "per_biomarker": concordance,
    }

    with open(sa_output / "sa12_summary.json", "w") as f:
        json.dump(summary, f, indent=2, default=str)

    logger.info(
        "  SA12 complete: %d/%d biomarkers concordant (ρ ≥ 0.7), mean ρ = %.3f",
        len(concordant),
        len(concordance),
        summary["mean_spearman_rho"] or 0.0,
    )
    return summary


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    from mcd_pipeline.stage0_data_prep.biomarker_definitions import get_available_biomarkers
    from mcd_pipeline.stage0_data_prep.build_analysis_dataset import build_analysis_dataset
    from mcd_pipeline.stage0_data_prep.feature_engineering import engineer_features

    df = build_analysis_dataset()
    biomarkers = get_available_biomarkers()
    bio_cols = [b.column for b in biomarkers.values() if b.column and b.column in df.columns]
    df = engineer_features(df, bio_cols)
    run_era5_land_comparison(df)
