"""
SA2: MODIS LST vs ERA5 — Urban Heat Island Sensitivity
======================================================

Re-runs Stage 1 using MODIS Land Surface Temperature (1 km resolution)
instead of ERA5 air temperature (28 km resolution). Differences indicate
urban heat island effects not captured at coarser resolution.

MODIS data is loaded from FINAL_DATASETS/CLIMATE_HEALTH_LINKAGE/MODIS_LST_LINKAGE.csv
(generated by mcd_pipeline/utils/extract_modis_lst.py using GEE MOD11A1 v6.1).

If the MODIS file does not exist, this analysis is flagged as DATA_UNAVAILABLE.
Run `python -m mcd_pipeline.utils.extract_modis_lst` to generate the data.

MCD reference: "MODIS LST vs ERA5 for urban heat island effects"
"""

import json
import logging
from pathlib import Path

import pandas as pd

from mcd_pipeline import config
from mcd_pipeline.sensitivity._sensitivity_core import (
    compare_lag_profiles,
    load_primary_lag_profiles,
    run_lightweight_stage1,
)

logger = logging.getLogger(__name__)

# MODIS lag column pattern: modis_lag0d_c, modis_lag1d_c, ...
MODIS_LAG_COLS = [f"modis_lag{d}d_c" for d in config.LAG_DAYS]
ERA5_LAG_COLS = [f"temp_lag_{d}d" for d in config.LAG_DAYS]


def _load_modis_data() -> pd.DataFrame | None:
    """Load MODIS LST linkage CSV if it exists."""
    if not config.MODIS_LST_CSV.exists():
        return None
    logger.info("Loading MODIS LST data from %s...", config.MODIS_LST_CSV)
    df = pd.read_csv(config.MODIS_LST_CSV, low_memory=False)
    logger.info("  MODIS rows: %d, coverage: %.1f%%",
                len(df),
                df["modis_lag0d_c"].notna().mean() * 100)
    return df


def _swap_era5_for_modis(df: pd.DataFrame, modis_df: pd.DataFrame) -> pd.DataFrame:
    """Replace ERA5 lag features in df with MODIS lag features.

    Merges MODIS data on (study_source, patient_id, visit_date), then
    renames modis_lag*d_c → temp_lag_*d so the existing Stage 1
    infrastructure works without modification.

    Returns a copy of df with MODIS-substituted temperature features.
    """
    # Normalise visit_date types before merging (df may have datetime, CSV has str)
    df = df.copy()
    df["visit_date"] = df["visit_date"].astype(str)
    modis_df = modis_df.copy()
    modis_df["visit_date"] = modis_df["visit_date"].astype(str)

    # Merge MODIS lags
    merged = df.merge(
        modis_df[["study_source", "patient_id", "visit_date"] + MODIS_LAG_COLS],
        on=["study_source", "patient_id", "visit_date"],
        how="left",
    )

    coverage = merged["modis_lag0d_c"].notna().mean() * 100
    logger.info("  MODIS merge coverage: %.1f%% of patient-visits", coverage)

    if coverage < 50:
        logger.warning(
            "  Low MODIS coverage (%.1f%%) — results will be based on subset only",
            coverage,
        )

    # Drop original ERA5 temp_lag_*d columns before renaming MODIS lags.
    # Both exist after the merge; keeping both creates duplicate column names,
    # which causes df["temp_lag_0d"] to return a DataFrame rather than a Series.
    era5_lag_cols = [f"temp_lag_{d}d" for d in config.LAG_DAYS]
    merged = merged.drop(columns=[c for c in era5_lag_cols if c in merged.columns])

    # Rename MODIS lags to match the standard temp_lag_*d naming
    rename_map = {
        f"modis_lag{d}d_c": f"temp_lag_{d}d"
        for d in config.LAG_DAYS
    }
    merged = merged.rename(columns=rename_map)

    # Drop rows without MODIS data (cloud gaps that weren't interpolated)
    n_before = len(merged)
    merged = merged.dropna(subset=["temp_lag_0d"])
    n_after = len(merged)
    logger.info("  Rows with MODIS data: %d/%d (%.1f%%)", n_after, n_before, 100 * n_after / n_before)

    return merged


def run_modis_comparison(
    df: pd.DataFrame,
    output_dir: Path = None,
    primary_profiles: dict = None,
) -> dict:
    """Re-run Stage 1 with MODIS LST features and compare SHAP profiles.

    If MODIS_LST_LINKAGE.csv is not present, reports data_unavailable.
    Otherwise substitutes MODIS lags for ERA5 lags and runs lightweight
    Stage 1, then computes Spearman ρ concordance per biomarker.

    Returns
    -------
    dict
        Per-biomarker concordance (SHAP profile: ERA5 vs MODIS),
        or status='data_unavailable' if MODIS data is absent.
    """
    output_dir = output_dir or (config.OUTPUT_ROOT / "sensitivity")
    sa_output = output_dir / "sa2_modis"
    sa_output.mkdir(parents=True, exist_ok=True)

    logger.info("=== SA2: MODIS LST vs ERA5 ===")

    # --- Check for MODIS data ---
    modis_df = _load_modis_data()

    if modis_df is None:
        msg = (
            f"MODIS LST file not found at {config.MODIS_LST_CSV}. "
            "Run `python -m mcd_pipeline.utils.extract_modis_lst` to generate it. "
            "Flagging as DATA_UNAVAILABLE."
        )
        logger.warning("  %s", msg)
        summary = {
            "sensitivity_analysis": "sa2_modis_vs_era5",
            "status": "data_unavailable",
            "description": msg,
            "modis_csv_path": str(config.MODIS_LST_CSV),
        }
        with open(sa_output / "sa2_summary.json", "w") as f:
            json.dump(summary, f, indent=2)
        return summary

    # --- Substitute MODIS for ERA5 in the analysis dataset ---
    df_modis = _swap_era5_for_modis(df, modis_df)

    if len(df_modis) < 1000:
        summary = {
            "sensitivity_analysis": "sa2_modis_vs_era5",
            "status": "insufficient_data",
            "n_rows_after_modis_merge": len(df_modis),
        }
        with open(sa_output / "sa2_summary.json", "w") as f:
            json.dump(summary, f, indent=2)
        return summary

    # --- Load primary ERA5 profiles ---
    if primary_profiles is None:
        primary_profiles = load_primary_lag_profiles()

    # --- Run lightweight Stage 1 with MODIS features ---
    logger.info("  Running lightweight Stage 1 with MODIS temperature features...")
    modis_results = run_lightweight_stage1(
        df_modis,
        output_dir=sa_output / "modis_stage1",
        label="sa2_modis",
    )

    # --- Compare MODIS SHAP profiles vs ERA5 primary profiles ---
    concordance = {}
    for bio_name, result in modis_results.items():
        if "error" in result:
            concordance[bio_name] = {"status": "failed", "error": result["error"]}
            continue

        lag_summary_modis = result.get("lag_summary")
        primary_lag = primary_profiles.get(bio_name)

        if lag_summary_modis is None or primary_lag is None:
            concordance[bio_name] = {"status": "no_comparison"}
            continue

        cmp = compare_lag_profiles(primary_lag, lag_summary_modis)
        cmp["cv_r2_modis"] = result.get("cv_r2")
        cmp["temporal_window_modis"] = result.get("temporal_window")
        concordance[bio_name] = cmp

    # --- Summary ---
    concordant = [b for b, c in concordance.items() if c.get("concordant", False)]
    rhos = [c["spearman_rho"] for c in concordance.values()
            if isinstance(c.get("spearman_rho"), float)]

    n_modis_rows = len(df_modis)
    n_patients_modis = df_modis["patient_id"].nunique() if "patient_id" in df_modis.columns else None

    summary = {
        "sensitivity_analysis": "sa2_modis_vs_era5",
        "status": "completed",
        "modis_csv_path": str(config.MODIS_LST_CSV),
        "n_rows_with_modis": n_modis_rows,
        "n_patients_with_modis": n_patients_modis,
        "n_biomarkers_tested": len(concordance),
        "n_concordant": len(concordant),
        "mean_spearman_rho": float(sum(rhos) / len(rhos)) if rhos else None,
        "concordant_biomarkers": concordant,
        "interpretation": (
            "High concordance (ρ>0.5) indicates ERA5 and MODIS capture similar "
            "lag-response patterns despite resolution difference. "
            "Low concordance highlights biomarkers where urban heat island effects "
            "at 1km resolution add meaningful information."
        ),
        "per_biomarker": concordance,
    }

    with open(sa_output / "sa2_summary.json", "w") as f:
        json.dump(summary, f, indent=2, default=str)

    logger.info(
        "=== SA2 complete: %d/%d concordant, mean ρ=%.3f ===",
        len(concordant), len(concordance),
        summary["mean_spearman_rho"] or 0,
    )

    return summary
