"""
SA3: Pollution-Adjusted Analysis — MERRA-2 PM2.5 as Covariate
=============================================================

Primary approach: loads real PM2.5 daily estimates from NASA MERRA-2
aerosol reanalysis (generated by mcd_pipeline/utils/extract_merra2_pollution.py
via Google Earth Engine) and includes them as covariates in Stage 1 alongside
temperature lag features.

If MERRA-2 data has not been extracted, falls back to a temporal restriction
to 2007–2021 (the post-monitoring-era proxy used in earlier drafts). This
fallback is clearly flagged in the output so results are not confused.

Research question: Do temperature–biomarker SHAP lag profiles change when
PM2.5 is included as a covariate? If Spearman ρ ≥ 0.7 vs primary (unadjusted)
results, temperature effects are robust to pollution confounding.

MCD reference: "pollution-adjusted subset (2007–2021, PM₂.₅/NO₂)"

Data source: NASA MERRA-2 `NASA/GSFC/MERRA/aer/2` via Google Earth Engine.
  Defensibility: MERRA-2 is the standard global atmospheric reanalysis for
  climate–health studies in regions without PM2.5 monitoring networks
  (Reddington et al. 2017 ACP; Hammer et al. 2020 Env. Sci. Technol.).
  Known to underestimate urban African PM2.5 — used for covariate adjustment
  (relative change), not absolute exposure estimation.
"""

import logging
from pathlib import Path

import numpy as np
import pandas as pd

from mcd_pipeline import config
from mcd_pipeline.sensitivity._sensitivity_core import (
    compare_lag_profiles,
    load_primary_lag_profiles,
    run_lightweight_stage1,
    run_subset_sensitivity,
)

logger = logging.getLogger(__name__)

# PM2.5 lag columns produced by extract_merra2_pollution.py
PM25_LAG_COLS = [f"pm25_lag{d}d_ugm3" for d in config.LAG_DAYS]


def _load_merra2_pm25() -> pd.DataFrame | None:
    """Load MERRA-2 PM2.5 linkage CSV if it exists.

    Returns None if the file has not been generated yet (triggers fallback).
    """
    path = config.MERRA2_POLLUTION_CSV
    if not path.exists():
        logger.warning(
            "MERRA-2 PM2.5 file not found at %s — "
            "run: python -m mcd_pipeline.utils.extract_merra2_pollution",
            path,
        )
        return None
    df = pd.read_csv(path, low_memory=False)
    n_rows = len(df)
    coverage = df[PM25_LAG_COLS[0]].notna().mean() * 100
    logger.info(
        "Loaded MERRA-2 PM2.5: %d rows, %.1f%% coverage", n_rows, coverage
    )
    logger.info(
        "  PM2.5 (lag0) range: %.2f – %.2f μg/m³, mean: %.2f μg/m³",
        df["pm25_lag0d_ugm3"].min(),
        df["pm25_lag0d_ugm3"].max(),
        df["pm25_lag0d_ugm3"].mean(),
    )
    return df


def _merge_pm25_to_df(df: pd.DataFrame, pm25_df: pd.DataFrame) -> pd.DataFrame:
    """Merge MERRA-2 PM2.5 lag columns into the analysis dataset.

    Joins on (study_source, patient_id, visit_date). Drops rows without
    any PM2.5 coverage (typically <5% of rows if extraction covered the
    full study period).
    """
    merge_keys = ["study_source", "patient_id", "visit_date"]
    # Only merge columns that exist in pm25_df
    pm25_cols = [c for c in PM25_LAG_COLS if c in pm25_df.columns]
    pm25_subset = pm25_df[merge_keys + pm25_cols + ["pm25_gap_flag"]].copy()

    # Normalise visit_date type (df may be datetime, MERRA-2 CSV is string)
    df = df.copy()
    df["visit_date"] = df["visit_date"].astype(str)
    pm25_subset["visit_date"] = pm25_subset["visit_date"].astype(str)

    merged = df.merge(pm25_subset, on=merge_keys, how="left")

    n_total = len(merged)
    n_with_pm25 = merged[pm25_cols[0]].notna().sum()
    n_dropped = n_total - n_with_pm25

    logger.info(
        "PM2.5 merge: %d/%d rows have PM2.5 data (%d without — excluded)",
        n_with_pm25, n_total, n_dropped,
    )

    # Restrict to rows with PM2.5 coverage for genuine pollution adjustment
    merged = merged[merged[pm25_cols[0]].notna()].copy()
    return merged, pm25_cols


def run_pollution_adjusted(
    df: pd.DataFrame,
    output_dir: Path = None,
    primary_profiles: dict = None,
) -> dict:
    """Run pollution-adjusted Stage 1 using MERRA-2 PM2.5 as covariate.

    Primary approach:
        - Merges MERRA-2 PM2.5 lag features into analysis dataset
        - Temporarily adds pm25_lag*d_ugm3 columns to CLINICAL_COVARIATES
          so Stage 1 XGBoost sees pollution alongside temperature
        - Compares temperature-only SHAP profiles vs pollution-adjusted profiles
        - If ρ ≥ 0.7, temperature effects are not confounded by PM2.5

    Fallback (if MERRA-2 CSV not found):
        - Restricts to post-2007 era (temporal proxy for monitoring period)
        - Flags output clearly as fallback mode

    Returns
    -------
    dict — concordance summary + per-biomarker results + methodology note.
    """
    output_dir = output_dir or (config.OUTPUT_ROOT / "sensitivity")
    sa_output = output_dir / "sa3_pollution"
    sa_output.mkdir(parents=True, exist_ok=True)

    if primary_profiles is None:
        primary_profiles = load_primary_lag_profiles()

    # --- Attempt primary approach: real MERRA-2 PM2.5 ---
    pm25_df = _load_merra2_pm25()

    if pm25_df is not None:
        logger.info(
            "=== SA3: Pollution-Adjusted Analysis (MERRA-2 PM2.5 covariates) ==="
        )

        df_pm25, pm25_cols = _merge_pm25_to_df(df, pm25_df)
        n_rows = len(df_pm25)

        if n_rows < 500:
            logger.warning(
                "  After PM2.5 merge only %d rows remain — falling back to "
                "temporal restriction", n_rows
            )
            pm25_df = None  # triggers fallback below
        else:
            # Temporarily wire PM2.5 columns into model features
            orig_clinical = list(config.CLINICAL_COVARIATES)
            # Add all available PM2.5 lag columns as covariates
            config.CLINICAL_COVARIATES = orig_clinical + pm25_cols

            try:
                results = run_lightweight_stage1(
                    df_pm25,
                    output_dir=sa_output / "pm25_adjusted",
                    label="sa3_pm25_adjusted",
                )
            finally:
                config.CLINICAL_COVARIATES = orig_clinical  # always restore

            # Compare vs primary
            comparisons = {}
            rhos = []
            for bio_name, result in results.items():
                if "error" in result or "lag_summary" not in result:
                    comparisons[bio_name] = {"status": result.get("error", "failed")}
                    continue
                primary_lag = primary_profiles.get(bio_name)
                if primary_lag is None:
                    comparisons[bio_name] = {"status": "no_primary_profile"}
                    continue
                cmp = compare_lag_profiles(primary_lag, result["lag_summary"])
                cmp["cv_r2"] = result.get("cv_r2")
                comparisons[bio_name] = cmp
                if isinstance(cmp.get("spearman_rho"), float) and not np.isnan(cmp["spearman_rho"]):
                    rhos.append(cmp["spearman_rho"])

            n_concordant = sum(
                1 for c in comparisons.values() if c.get("concordant", False)
            )
            mean_rho = float(np.mean(rhos)) if rhos else None

            logger.info(
                "=== SA3 PM2.5-adjusted complete: ρ=%.3f, %d/%d biomarkers concordant ===",
                mean_rho or 0, n_concordant, len(comparisons),
            )

            summary = {
                "sensitivity_analysis": "sa3_pollution_adjusted",
                "analysis_mode": "merra2_pm25_covariate",
                "description": (
                    "Temperature–biomarker Stage 1 re-run with MERRA-2 PM2.5 "
                    "lag covariates. Tests whether temperature SHAP profiles are "
                    "robust to air pollution confounding."
                ),
                "data_source": "NASA MERRA-2 aer/2 via Google Earth Engine",
                "merra2_resolution_km": 55,
                "n_rows_with_pm25": n_rows,
                "pm25_lag_cols": pm25_cols,
                "pm25_mean_ugm3": float(df_pm25["pm25_lag0d_ugm3"].mean()),
                "pm25_range_ugm3": [
                    float(df_pm25["pm25_lag0d_ugm3"].min()),
                    float(df_pm25["pm25_lag0d_ugm3"].max()),
                ],
                "concordance": {
                    "n_biomarkers": len(comparisons),
                    "n_concordant": n_concordant,
                    "mean_spearman_rho": mean_rho,
                    "min_spearman_rho": float(np.min(rhos)) if rhos else None,
                },
                "per_biomarker": comparisons,
                "methodological_note": (
                    "SA3 uses real PM2.5 estimates from NASA MERRA-2 aerosol "
                    "reanalysis (~55 km resolution) as additional covariates in "
                    "the Stage 1 XGBoost model. MERRA-2 is known to underestimate "
                    "absolute PM2.5 in African cities (Hammer et al. 2020), but "
                    "captures relative temporal variation. High Spearman ρ vs "
                    "primary results (≥0.7) indicates temperature effects are not "
                    "confounded by the modelled PM2.5 signal. Limitations: no "
                    "ground-level PM2.5 monitoring network covers the study area "
                    "continuously; MERRA-2 does not distinguish PM2.5 sources "
                    "(industrial, traffic, biomass burning)."
                ),
            }

            import json
            with open(sa_output / "sa3_summary.json", "w") as f:
                json.dump(summary, f, indent=2, default=str)

            return summary

    # --- Fallback: temporal restriction to 2007–2021 ---
    logger.info(
        "=== SA3: Temporal Restriction Fallback (%d–%d) ===",
        config.POLLUTION_DATA_START_YEAR,
        config.POLLUTION_DATA_END_YEAR,
    )

    mask = (
        (df["year"] >= config.POLLUTION_DATA_START_YEAR)
        & (df["year"] <= config.POLLUTION_DATA_END_YEAR)
    )

    result = run_subset_sensitivity(
        df_full=df,
        subset_mask=mask,
        sa_name="sa3_pollution",
        sa_label=(
            f"Temporal restriction "
            f"({config.POLLUTION_DATA_START_YEAR}–{config.POLLUTION_DATA_END_YEAR})"
        ),
        output_dir=output_dir,
        primary_profiles=primary_profiles,
    )

    result["analysis_mode"] = "temporal_restriction_fallback"
    result["methodological_note"] = (
        "FALLBACK MODE: MERRA-2 PM2.5 data not found. "
        "SA3 fell back to temporal period restriction (2007–2021), "
        "not explicit pollution-adjusted analysis (no PM2.5/NO2 covariates "
        "in model). Run mcd_pipeline/utils/extract_merra2_pollution.py first "
        "to enable genuine pollution adjustment. "
        "Interpretation of fallback: tests whether results hold in the period "
        "when air quality monitoring was active in Johannesburg."
    )

    import json
    with open(sa_output / "sa3_summary.json", "w") as f:
        json.dump(result, f, indent=2, default=str)

    return result
